import XCTest

final class RuntimeManagerSourceTests: XCTestCase {
    func testProcessFirstModeUsesDirectInitTransport() throws {
        let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath, isDirectory: true)
        let source = try String(contentsOf: root.appendingPathComponent("Sources/mslCore/RuntimeManager.swift"), encoding: .utf8)

        XCTAssertTrue(source.contains("if metadata.resolvedStartupMode() == .processFirst"))
        XCTAssertTrue(source.contains("try runProcessFirstCommand("))
        XCTAssertTrue(source.contains("transport\": usePTY ? \"direct_init_pty\" : \"direct_init_proc\""))
        XCTAssertTrue(source.contains("\"transport\": \"direct_init_exec\""))
        XCTAssertTrue(source.contains("ssh is not supported for this instance mode"))
    }

    func testNerdctlUsesContainerRuntimeDaemonPath() throws {
        let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath, isDirectory: true)
        let source = try String(contentsOf: root.appendingPathComponent("Sources/mslCore/RuntimeManager.swift"), encoding: .utf8)
        let portSource = try String(contentsOf: root.appendingPathComponent("Sources/mslCore/NerdctlPortPublishing.swift"), encoding: .utf8)
        let daemonSource = try String(contentsOf: root.appendingPathComponent("Sources/mslCore/DaemonServer.swift"), encoding: .utf8)

        XCTAssertTrue(source.contains("public func runNerdctl"))
        XCTAssertTrue(source.contains("resolveContainerRuntimeTarget(explicitInstanceName: instanceName)"))
        XCTAssertTrue(source.contains("container runtime artifact is not installed; use `make build-container-runtime`"))
        XCTAssertTrue(source.contains("container runtime uses legacy disk.raw storage; use `make build-container-runtime`"))
        XCTAssertTrue(source.contains("metadata.resolvedRootMode() == .readonlyBaseCowState"))
        XCTAssertTrue(source.contains("paths.distroBaseDiskFile(named: resolvedName)"))
        XCTAssertTrue(source.contains("paths.distroStateDiskFile(named: resolvedName)"))
        XCTAssertTrue(source.contains("try daemonClient.ensureConnected("))
        XCTAssertTrue(source.contains("expectedInstanceName: target.instanceName"))
        XCTAssertTrue(source.contains("executeNerdctlViaDaemon("))
        XCTAssertTrue(source.contains("op: \"session_register\""))
        XCTAssertTrue(source.contains("op: \"pty_open\""))
        XCTAssertTrue(source.contains("op: \"proc_open\""))
        XCTAssertTrue(source.contains("SessionStreamBridge.runPty(\n                daemonClient: daemonClient"))
        XCTAssertTrue(source.contains("SessionStreamBridge.runProc(\n            daemonClient: daemonClient"))
        XCTAssertFalse(source.contains("let runner = try makeDirectVirtualMachineRunner(metadataURL: target.metadataURL, instanceName: target.instanceName)"))
        XCTAssertFalse(source.contains("runner.requestStopRunningVM()"))
        XCTAssertFalse(source.contains("runner.stopRunningVM()\n        Foundation.exit(exitCode)"))
        XCTAssertTrue(source.contains("ensureContainerRuntimeServiceManagerInitialized("))
        XCTAssertTrue(source.contains("/run/openrc/softlevel"))
        XCTAssertTrue(source.contains("private func ensureContainerRuntimeService("))
        XCTAssertTrue(source.contains("private func nerdctlNeedsBuildkit(argv: [String]) -> Bool"))
        XCTAssertTrue(source.contains("waitForContainerRuntimeSocketIfNeeded("))
        XCTAssertTrue(source.contains("/run/containerd/containerd.sock"))
        XCTAssertTrue(source.contains("/run/buildkit/buildkitd.sock"))
        XCTAssertTrue(source.contains("reconcileDirectRuntimeDNS("))
        XCTAssertTrue(source.contains("let workspacePlan = try resolveNerdctlWorkspacePlan(argv: argv)"))
        XCTAssertTrue(source.contains("applyNerdctlPublishedPortMappingsIfNeeded("))
        XCTAssertTrue(source.contains("NerdctlPortPublishing.directForwardMappings(from: argv, instanceName: instanceName)"))
        XCTAssertTrue(daemonSource.contains("InitRelayPortForwardingManager(logger: logger, initClient: client)"))
        XCTAssertTrue(daemonSource.contains("initialMetadata.resolvedWorkloadKind() == .containerRuntime"))
        XCTAssertTrue(portSource.contains("source: \"nerdctl\""))
        XCTAssertFalse(source.contains("published ports require vmnet"))
        XCTAssertTrue(source.contains("if workspacePlan.requiresWorkspace"))
        XCTAssertTrue(source.contains("build context not accessible from current workspace"))
        XCTAssertTrue(source.contains("workspace mount failed for nerdctl"))
        XCTAssertTrue(source.contains("evaluateNerdctlWorkspacePolicy("))
        XCTAssertTrue(source.contains("prepareWorkspaceIfNeeded(policy: workspacePolicy, instanceName: target.instanceName)"))
        XCTAssertTrue(source.contains("op: \"host_share_prepare\""))
        XCTAssertTrue(source.contains("container_runtime_direct_mount"))
        XCTAssertTrue(source.contains("op: \"dns_reconcile\""))
        XCTAssertTrue(source.contains("op: \"dns_healthcheck\""))
        XCTAssertTrue(source.contains("private func ensureContainerRuntimeCachePolicy("))
        XCTAssertTrue(source.contains("marker=\"$marker_dir/container-runtime-cache-policy\""))
        XCTAssertTrue(source.contains("policy=native-v1"))
        XCTAssertTrue(source.contains("rm -rf /var/lib/containerd /var/lib/buildkit"))
        XCTAssertTrue(source.contains("let effectiveNerdctlArgs = applyDefaultNerdctlSnapshotterIfNeeded(argv)"))
        XCTAssertTrue(source.contains("[\"/usr/local/bin/nerdctl\"] + effectiveNerdctlArgs"))
        XCTAssertTrue(source.contains("\"CONTAINERD_ADDRESS\": \"/run/containerd/containerd.sock\""))
        XCTAssertTrue(source.contains("\"BUILDKIT_HOST\": \"unix:///run/buildkit/buildkitd.sock\""))
        XCTAssertTrue(source.contains("\"CONTAINERD_SNAPSHOTTER\": \"native\""))
        XCTAssertTrue(source.contains("return [\"--snapshotter\", \"native\"] + argv"))
        XCTAssertTrue(source.contains("arg == \"--snapshotter\" || arg.hasPrefix(\"--snapshotter=\")"))
        XCTAssertTrue(source.contains("let terminalMode = try resolveNerdctlTerminalModeForExecution(argv: effectiveNerdctlArgs)"))
        XCTAssertTrue(source.contains("case .interactivePTY, .displayPTY:"))
        XCTAssertTrue(source.contains("attachInput: terminalMode == .interactivePTY"))
        XCTAssertTrue(source.contains("private func nerdctlNeedsConfirmationPrompt(argv: [String]) -> Bool"))
        XCTAssertTrue(source.contains("nerdctl prune requires an interactive terminal; rerun with --force"))
        XCTAssertTrue(source.contains("executeDirectInitStreamingProc("))
        XCTAssertTrue(source.contains("\"transport\": \"direct_init_proc_stream\""))
        XCTAssertTrue(source.contains("\"transport\": \"daemon_proc_stream\""))
        XCTAssertTrue(source.contains("\"transport\": terminalMode.transport"))
        XCTAssertTrue(source.contains("private func flushContainerRuntimeDisk("))
        XCTAssertTrue(source.contains("argv: [\"/bin/sync\"]"))
        XCTAssertTrue(source.contains("logPrefix: \"container_runtime_flush\""))
        XCTAssertFalse(source.contains("runNerdctlWithCorruptCacheRetry("))
        XCTAssertFalse(source.contains("finalizeContainerRuntimeVM("))
        XCTAssertFalse(source.contains("[\"/usr/local/bin/nerdctl\", \"rmi\", \"--force\", imageRef]"))
        XCTAssertFalse(source.contains("isNerdctlEntrypointStatMissingError("))
        XCTAssertTrue(source.contains("\"TERM\": ProcessInfo.processInfo.environment[\"TERM\"].flatMap"))
        XCTAssertTrue(source.contains("env[\"COLORTERM\"] = colorTerm"))
        XCTAssertTrue(source.contains("client.procOpen("))
        XCTAssertTrue(source.contains("SessionStreamBridge.runProc("))
        XCTAssertTrue(source.contains("private func resolveNerdctlTerminalMode"))
        XCTAssertTrue(source.contains("private func nerdctlNeedsDisplayPTY"))
        XCTAssertTrue(source.contains("private func nerdctlNeedsBuildkit"))
        XCTAssertTrue(source.contains("case \"run\", \"pull\", \"push\", \"build\":"))
        XCTAssertTrue(source.contains("composeCommand == \"up\" || composeCommand == \"build\" || composeCommand == \"pull\""))
        XCTAssertTrue(source.contains("guard hostHasOutputTTY() else { return .streamingProc }"))
        XCTAssertTrue(source.contains("hostHasInteractiveTTY() ? .interactivePTY : .displayPTY"))
        XCTAssertTrue(source.contains("private enum NerdctlTerminalMode"))
        XCTAssertTrue(source.contains("direct_init_display_pty"))
        XCTAssertTrue(source.contains("direct_init_interactive_pty"))
        XCTAssertTrue(source.contains("let hostTerminal = attachInput ? HostTerminalState.capture() : nil"))
        XCTAssertTrue(source.contains("if attachInput {\n                enterRawModeForShell()"))
    }

    func testContainerResetUsesStateResetPath() throws {
        let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath, isDirectory: true)
        let source = try String(contentsOf: root.appendingPathComponent("Sources/mslCore/RuntimeManager.swift"), encoding: .utf8)

        XCTAssertTrue(source.contains("public func runContainerReset(instanceName rawName: String?) throws -> Never"))
        XCTAssertTrue(source.contains("public func resetContainerState(instanceName rawName: String?) throws -> URL"))
        XCTAssertTrue(source.contains("distributionManager.resolveContainerRuntimeInstanceName()"))
        XCTAssertTrue(source.contains("try resolveContainerRuntimeTarget(explicitInstanceName: resolvedName)"))
        XCTAssertTrue(source.contains("distributionManager.resetWritableState(name: resolvedName)"))
        XCTAssertTrue(source.contains("container state reset:"))
    }

    func testDefaultInstanceIsNotAutoSetForReservedInternalInstances() throws {
        let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath, isDirectory: true)
        let source = try String(contentsOf: root.appendingPathComponent("Sources/mslCore/RuntimeManager.swift"), encoding: .utf8)
        XCTAssertTrue(source.contains("if distributionManager.isReservedInternalInstanceName(name)"))
    }

    func testStatusUsesPublicDefaultAndMergedEntries() throws {
        let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath, isDirectory: true)
        let source = try String(contentsOf: root.appendingPathComponent("Sources/mslCore/RuntimeManager.swift"), encoding: .utf8)

        XCTAssertTrue(source.contains("var statusEntriesByInstance = Dictionary(uniqueKeysWithValues: instances.map"))
        XCTAssertTrue(source.contains("statusEntriesByInstance[entry.instance] = entry"))
        XCTAssertTrue(source.contains("let publicBootableInstances = Set("))
        XCTAssertTrue(source.contains("for instance in publicBootableInstances where statusEntriesByInstance[instance] == nil"))
        XCTAssertTrue(source.contains("targetInstance = try resolveRuntimeTarget(explicitInstanceName: nil).instanceName"))
        XCTAssertTrue(source.contains("let searchableEntries = instanceName == nil ? publicStatusEntries : allStatusEntries"))
    }

    func testExecutablePathResolutionDoesNotFollowSwiftPMBuildSymlink() throws {
        let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath, isDirectory: true)
        let source = try String(contentsOf: root.appendingPathComponent("Sources/mslCore/RuntimeManager.swift"), encoding: .utf8)
        guard let functionRange = source.range(of: "private static func resolveExecutablePath"),
              let nextRange = source.range(of: "\n    private struct WorkspaceStartupPolicyDecision", range: functionRange.upperBound..<source.endIndex) else {
            return XCTFail("resolveExecutablePath function not found")
        }
        let body = String(source[functionRange.lowerBound..<nextRange.lowerBound])

        XCTAssertTrue(body.contains(".standardizedFileURL"))
        XCTAssertFalse(body.contains(".resolvingSymlinksInPath()"))
    }
}
